// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deckbuilder.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710174631_RequiredCardFields")]
    partial class RequiredCardFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deckbuilder.Server.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ColorIdentity")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Power")
                        .HasColumnType("int");

                    b.Property<string>("RulesText")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("TcgPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Toughness")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Deckbuilder.Server.Entities.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
