// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deckbuilder.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250625215933_CardFix")]
    partial class CardFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deckbuilder.Server.Models.Card", b =>
                {
                    b.Property<int>("cardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cardId"));

                    b.Property<string>("cardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("colorIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("manaCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("power")
                        .HasColumnType("int");

                    b.Property<int>("toughness")
                        .HasColumnType("int");

                    b.HasKey("cardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Deckbuilder.Server.Models.Decks", b =>
                {
                    b.Property<int>("deckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deckId"));

                    b.Property<string>("colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("deckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("format")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("deckId");

                    b.ToTable("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
